# Generated by Django 5.2.4 on 2026-09-12 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_options_alter_member_address_and_more'),
        ('products', '0003_alter_product_options_alter_product_cost_price_and_more'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsale',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mahsulot sotuvi', 'verbose_name_plural': 'Mahsulot sotuvlari'},
        ),
        migrations.AlterModelOptions(
            name='productsaleitem',
            options={'verbose_name': 'Sotuv qatori', 'verbose_name_plural': 'Sotuv qatorlari'},
        ),
        migrations.AlterField(
            model_name='productsale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_sales', to='members.member', verbose_name="A'zo"),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jami summa'),
        ),
        migrations.AlterField(
            model_name='productsaleitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Qator summasi'),
        ),
        migrations.AlterField(
            model_name='productsaleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='productsaleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Miqdor'),
        ),
        migrations.AlterField(
            model_name='productsaleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.productsale', verbose_name='Sotuv'),
        ),
        migrations.AlterField(
            model_name='productsaleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Birlik narxi'),
        ),
    ]
