# Generated by Django 5.2.4 on 2026-09-12 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('members', '0003_alter_member_options_alter_member_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgertransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Moliyaviy operatsiya', 'verbose_name_plural': 'Moliyaviy operatsiyalar'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': "To'lov", 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan'),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='direction',
            field=models.CharField(choices=[('DEBIT', 'Qarz (+)'), ('CREDIT', "To'lov (-)")], max_length=6, verbose_name="Yo'nalish"),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='members.member', verbose_name="A'zo"),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='reference_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name="Bog'liq obyekt turi"),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='reference_object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Bog'liq obyekt ID"),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='reversed_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverses', to='billing.ledgertransaction', verbose_name='Bekor qilgan yozuv'),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('MEMBERSHIP_CHARGE', "A'zolik to'lovi"), ('DAILY_CHARGE', "Kunlik to'lov"), ('PRODUCT_CHARGE', 'Mahsulot sotuvi'), ('MANUAL_CHARGE', "Qo'lda qo'shilgan qarz"), ('PAYMENT', "To'lov"), ('ADJUSTMENT', 'Tuzatish')], max_length=20, verbose_name='Operatsiya turi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Keyingi qoldiq'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Oldingi qoldiq'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ledger_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='billing.ledgertransaction', verbose_name='Buxgalteriya yozuvi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='members.member', verbose_name="A'zo"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Plastik karta'), ('TRANSFER', "O'tkazma"), ('OTHER', 'Boshqa')], default='CASH', max_length=10, verbose_name="To'lov usuli"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chek raqami'),
        ),
    ]
