# Generated by Django 5.2.4 on 2026-09-12 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_options_alter_member_address_and_more'),
        ('memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-start_date'], 'verbose_name': "A'zolik", 'verbose_name_plural': "A'zoliklar"},
        ),
        migrations.AlterModelOptions(
            name='membershipplan',
            options={'ordering': ['plan_type', 'name'], 'verbose_name': "A'zolik rejasi", 'verbose_name_plural': "A'zolik rejalari"},
        ),
        migrations.AlterField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(verbose_name='Tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='members.member', verbose_name="A'zo"),
        ),
        migrations.AlterField(
            model_name='membership',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='memberships.membershipplan', verbose_name='Reja'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotib olish narxi'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(verbose_name='Boshlanish sanasi'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Faol'), ('EXPIRED', 'Muddati tugagan'), ('CANCELLED', 'Bekor qilingan')], default='ACTIVE', max_length=10, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='duration_days',
            field=models.PositiveIntegerField(help_text='1 for daily plans, e.g. 30 for monthly.', verbose_name='Davomiyligi (kun)'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='plan_type',
            field=models.CharField(choices=[('DAILY', 'Kunlik'), ('MONTHLY', 'Oylik')], max_length=10, verbose_name='Reja turi'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi'),
        ),
    ]
