# Generated by Django 5.2.4 on 2026-09-12 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0003_alter_product_options_alter_product_cost_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ombor harakati', 'verbose_name_plural': 'Ombor harakatlari'},
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity_after',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Keyingi qoldiq'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity_delta',
            field=models.DecimalField(decimal_places=3, help_text='Positive=in, negative=out', max_digits=12, verbose_name="Miqdor o'zgarishi"),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('RESTOCK', 'Yangi yetkazib berish'), ('SALE', 'Sotuv'), ('CORRECTION', 'Tuzatish'), ('DAMAGE', 'Yaroqsiz/Zarar'), ('OTHER', 'Boshqa')], max_length=20, verbose_name='Sabab'),
        ),
    ]
