# Generated by Django 5.0.9 on 2026-08-25 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('members', '0001_initial'),
        ('memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_attendance_per_member_per_day',
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('check_out__isnull', True)), fields=('member',), name='unique_open_attendance_per_member'),
        ),
    ]
